---
title: "Simulated Bivariate Ornstein–Uhlenbeck Model"
author: "Ivan Jacob Agaloos Pesigan"
date: "2023-11-14"
bibliography: "vignettes.bib"
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
nocite: |
  @Chow-Losardo-Park-etal-2023
  @Ou-Hunter-Chow-2019
  @Uhlenbeck-Ornstein-1930
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Simulated Bivariate Ornstein–Uhlenbeck Model}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- vignettes/sim-bivariate-ou.Rmd is generated from .setup/vignettes/sim-bivariate-ou.Rmd.orig. Please edit that file -->

## The Ornstein–Uhlenbeck Model

The measurement model is given by

\begin{equation}
  \mathbf{y}_{i, t}
  =
  \boldsymbol{\nu}
  +
  \boldsymbol{\Lambda}
  \boldsymbol{\eta}_{i, t} 
  +
  \boldsymbol{\varepsilon}_{i, t}
  \quad
  \mathrm{with}
  \quad
  \boldsymbol{\varepsilon}_{i, t}
  \sim
  \mathcal{N}
  \left(
  \mathbf{0},
  \boldsymbol{\Theta}
  \right)
\end{equation}

where $\mathbf{y}_{i, t}$, $\boldsymbol{\eta}_{i, t}$,
and $\boldsymbol{\varepsilon}_{i, t}$
are random variables and $\boldsymbol{\nu}$,
$\boldsymbol{\Lambda}$,
and $\boldsymbol{\Theta}$ are model parameters.
$\mathbf{y}_{i, t}$ is a vector of observed random variables
at time $t$ and individual $i$,
$\boldsymbol{\eta}_{i, t}$ is a vector of latent random variables
at time $t$ and individual $i$,
and $\boldsymbol{\varepsilon}_{i, t}$
is a vector of random measurement errors
at time $t$ and individual $i$,
while $\boldsymbol{\nu}$ is a vector of intercept,
$\boldsymbol{\Lambda}$ is a matrix of factor loadings,
and $\boldsymbol{\Theta}$ is the covariance matrix of
$\boldsymbol{\varepsilon}$.

The dynamic structure is given by

\begin{equation}
  \mathrm{d} \boldsymbol{\eta}_{i, t}
  =
  \boldsymbol{\Phi}
  \left(
  \boldsymbol{\mu}
  -
  \boldsymbol{\eta}_{i, t}
  \right)
  \mathrm{d}t
  +
  \boldsymbol{\Sigma}^{\frac{1}{2}}
  \mathrm{d}
  \mathbf{W}_{i, t}
\end{equation}

where $\boldsymbol{\mu}$ is the long-term mean or equilibrium level,
$\boldsymbol{\Phi}$ is the rate of mean reversion,
determining how quickly the variable returns to its mean,
$\boldsymbol{\Sigma}$ is the matrix of volatility
or randomness in the process, and $\mathrm{d}\boldsymbol{W}$
is a Wiener process or Brownian motion,
which represents random fluctuations.

## Data Generation

### Notation



Let the measurement model intecept vector $\boldsymbol{\nu}$ be given by

\begin{equation}
\boldsymbol{\nu}
=
\left(
\begin{array}{c}
  0 \\
  0 \\
\end{array}
\right) .
\end{equation}

Let the factor loadings matrix $\boldsymbol{\Lambda}$ be given by

\begin{equation}
\boldsymbol{\Lambda}
=
\left(
\begin{array}{cc}
  1 & 0 \\
  0 & 1 \\
\end{array}
\right) .
\end{equation}

Let the measurement error covariance matrix $\boldsymbol{\Theta}$ be given by

\begin{equation}
\boldsymbol{\Theta}
=
\left(
\begin{array}{cc}
  0.5 & 0 \\
  0 & 0.5 \\
\end{array}
\right) .
\end{equation}

Let the initial condition
$\boldsymbol{\eta}_{0}$
be given by

\begin{equation}
\boldsymbol{\eta}_{0} \sim \mathcal{N} \left( \boldsymbol{\mu}_{\boldsymbol{\eta} \mid 0}, \boldsymbol{\Sigma}_{\boldsymbol{\eta} \mid 0} \right)
\end{equation}

\begin{equation}
\boldsymbol{\mu}_{\boldsymbol{\eta} \mid 0}
=
\left(
\begin{array}{c}
  -3 \\
  1.5 \\
\end{array}
\right)
\end{equation}

\begin{equation}
\boldsymbol{\Sigma}_{\boldsymbol{\eta} \mid 0}
=
\left(
\begin{array}{cc}
  1 & 0 \\
  0 & 1 \\
\end{array}
\right) .
\end{equation}

Let the long-term mean vector $\boldsymbol{\mu}$ be given by

\begin{equation}
\boldsymbol{\mu}
=
\left(
\begin{array}{c}
  5.76 \\
  5.18 \\
\end{array}
\right) .
\end{equation}

Let the rate of mean reversion matrix $\boldsymbol{\Phi}$ be given by

\begin{equation}
\boldsymbol{\Phi}
=
\left(
\begin{array}{cc}
  0.1 & -0.05 \\
  -0.05 & 0.1 \\
\end{array}
\right) .
\end{equation}

Let the dynamic process noise covariance matrix $\boldsymbol{\Sigma}$ be given by

\begin{equation}
\boldsymbol{\Sigma}
=
\left(
\begin{array}{cc}
  2.79 & 0.06 \\
  0.06 & 3.27 \\
\end{array}
\right) .
\end{equation}

### R Function Arguments


```r
n
```

```
## [1] 5
```

```r
time
```

```
## [1] 500
```

```r
delta_t
```

```
## [1] 0.1
```

```r
mu0
```

```
## [1] -3.0  1.5
```

```r
sigma0
```

```
##      [,1] [,2]
## [1,]    1    0
## [2,]    0    1
```

```r
mu
```

```
## [1] 5.76 5.18
```

```r
phi
```

```
##       [,1]  [,2]
## [1,]  0.10 -0.05
## [2,] -0.05  0.10
```

```r
sigma
```

```
##      [,1] [,2]
## [1,] 2.79 0.06
## [2,] 0.06 3.27
```

```r
nu
```

```
## [1] 0 0
```

```r
lambda
```

```
##      [,1] [,2]
## [1,]    1    0
## [2,]    0    1
```

```r
theta
```

```
##      [,1] [,2]
## [1,]  0.5  0.0
## [2,]  0.0  0.5
```

### Using the simStateSpace::SimSSMVARFixed Function to Simulate Data


```r
if (!require("remotes")) install.packages("remotes")
remotes::install_github("ijapesigan/simStateSpace")
```


```r
library(simStateSpace)
set.seed(42)
data <- Sim2Matrix(
  SimSSMOUFixed(
    n = n,
    mu0 = mu0,
    sigma0_sqrt = chol(sigma0),
    mu = mu,
    phi = phi,
    sigma_sqrt = chol(sigma),
    nu = nu,
    lambda = lambda,
    theta_sqrt = chol(theta),
    delta_t = delta_t,
    time = time,
    burn_in = 0
  )
)
head(data)
```

```
##             y1       y2 time id
## [1,] -1.963528 2.532490  0.0  1
## [2,] -2.551147 2.860833  0.1  1
## [3,] -3.267033 2.904142  0.2  1
## [4,] -4.042884 5.179311  0.3  1
## [5,] -3.788725 3.874309  0.4  1
## [6,] -3.209223 4.531096  0.5  1
```

## Prepare Data


```r
data <- fitOU::DataOU(
  data = data,
  observed = c("y1", "y2"),
  id = "id",
  time = "time",
  center = FALSE,
  scale = FALSE
)
summary(data)
```

```
##        id         time             y1                y2          
##  Min.   :1   Min.   : 0.00   Min.   :-11.613   Min.   :-17.0447  
##  1st Qu.:2   1st Qu.:12.47   1st Qu.: -1.769   1st Qu.: -0.6119  
##  Median :3   Median :24.95   Median :  1.236   Median :  3.8133  
##  Mean   :3   Mean   :24.95   Mean   :  2.108   Mean   :  3.2086  
##  3rd Qu.:4   3rd Qu.:37.42   3rd Qu.:  5.530   3rd Qu.:  8.0518  
##  Max.   :5   Max.   :49.90   Max.   : 18.704   Max.   : 14.4450
```

## Specify Model


```r
model <- fitOU::ModelOU(
  data = data,
  observed = c("y1", "y2"),
  id = "id",
  time = "time"
)
str(model)
```

```
## Formal class 'dynrModel' [package "dynr"] with 17 slots
##   ..@ dynamics      :Formal class 'dynrDynamicsFormula' [package "dynr"] with 13 slots
##   .. .. ..@ c.string            : chr "void function_dx_dt(double t, size_t regime, const gsl_vector *x, double *param, size_t n_param, const gsl_vect"| __truncated__
##   .. .. ..@ startval            : Named num [1:6] 2.11 3.21 0.1 0.1 0.1 ...
##   .. .. .. ..- attr(*, "names")= chr [1:6] "mu_1" "mu_2" "phi_11" "phi_21" ...
##   .. .. ..@ paramnames          : chr [1:6] "mu_1" "mu_2" "phi_11" "phi_21" ...
##   .. .. ..@ formula             :List of 1
##   .. .. .. ..$ :List of 2
##   .. .. .. .. ..$ :Class 'formula'  language eta_1 ~ param[2] * (param[0] - eta_1) + param[4] * (param[1] - eta_2)
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf9d11ff8> 
##   .. .. .. .. ..$ :Class 'formula'  language eta_2 ~ param[3] * (param[0] - eta_1) + param[5] * (param[1] - eta_2)
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf9d11ff8> 
##   .. .. ..@ jacobian            :List of 1
##   .. .. .. ..$ :List of 4
##   .. .. .. .. ..$ :Class 'formula'  language eta_1 ~ eta_1 ~ -param[2]
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf9d22ab8> 
##   .. .. .. .. ..$ :Class 'formula'  language eta_1 ~ eta_2 ~ -param[4]
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf9d22ab8> 
##   .. .. .. .. ..$ :Class 'formula'  language eta_2 ~ eta_1 ~ -param[3]
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf9d22ab8> 
##   .. .. .. .. ..$ :Class 'formula'  language eta_2 ~ eta_2 ~ -param[5]
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf9d22ab8> 
##   .. .. ..@ formulaOriginal     :List of 1
##   .. .. .. ..$ :List of 2
##   .. .. .. .. ..$ :Class 'formula'  language eta_1 ~ phi_11 * (mu_1 - eta_1) + phi_12 * (mu_2 - eta_2)
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf76467e0> 
##   .. .. .. .. ..$ :Class 'formula'  language eta_2 ~ phi_21 * (mu_1 - eta_1) + phi_22 * (mu_2 - eta_2)
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf76467e0> 
##   .. .. ..@ jacobianOriginal    :List of 1
##   .. .. .. ..$ :List of 4
##   .. .. .. .. ..$ :Class 'formula'  language eta_1 ~ eta_1 ~ -phi_11
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf785c048> 
##   .. .. .. .. ..$ :Class 'formula'  language eta_1 ~ eta_2 ~ -phi_12
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf785c048> 
##   .. .. .. .. ..$ :Class 'formula'  language eta_2 ~ eta_1 ~ -phi_21
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf785c048> 
##   .. .. .. .. ..$ :Class 'formula'  language eta_2 ~ eta_2 ~ -phi_22
##   .. .. .. .. .. .. ..- attr(*, ".Environment")=<environment: 0x561cf785c048> 
##   .. .. ..@ random.names        : chr(0) 
##   .. .. ..@ theta.formula       : list()
##   .. .. ..@ isContinuousTime    : logi TRUE
##   .. .. ..@ saem                : logi(0) 
##   .. .. ..@ random.params.inicov: num[0 , 0 ] 
##   .. .. ..@ random.values.inicov: num[0 , 0 ] 
##   ..@ measurement   :Formal class 'dynrMeasurement' [package "dynr"] with 12 slots
##   .. .. ..@ c.string   : chr "void function_measurement(size_t t, size_t regime, double *param, const gsl_vector *eta, const gsl_vector *co_v"| __truncated__
##   .. .. ..@ startval   : num(0) 
##   .. .. ..@ paramnames : chr(0) 
##   .. .. ..@ values.load:List of 1
##   .. .. .. ..$ : num [1:2, 1:2] 1 0 0 1
##   .. .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. .. ..$ : chr [1:2] "y1" "y2"
##   .. .. .. .. .. ..$ : chr [1:2] "eta_1" "eta_2"
##   .. .. ..@ params.load:List of 1
##   .. .. .. ..$ : int [1:2, 1:2] 0 0 0 0
##   .. .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. .. ..$ : chr [1:2] "y1" "y2"
##   .. .. .. .. .. ..$ : chr [1:2] "eta_1" "eta_2"
##   .. .. ..@ values.exo : list()
##   .. .. ..@ params.exo : list()
##   .. .. ..@ values.int : list()
##   .. .. ..@ params.int : list()
##   .. .. ..@ state.names: chr [1:2] "eta_1" "eta_2"
##   .. .. ..@ obs.names  : chr [1:2] "y1" "y2"
##   .. .. ..@ exo.names  : chr(0) 
##   ..@ noise         :Formal class 'dynrNoise' [package "dynr"] with 9 slots
##   .. .. ..@ c.string               : chr "void function_noise_cov(size_t t, size_t regime, double *param, gsl_matrix *y_noise_cov, gsl_matrix *eta_noise_"| __truncated__
##   .. .. ..@ startval               : num [1:5] 0 0 0 0 0
##   .. .. ..@ paramnames             : chr [1:5] "sigma_11" "sigma_12" "sigma_22" "theta_11" ...
##   .. .. ..@ values.latent          :List of 1
##   .. .. .. ..$ : num [1:2, 1:2] 1 0 0 1
##   .. .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. .. ..$ : NULL
##   .. .. .. .. .. ..$ : NULL
##   .. .. ..@ params.latent          :List of 1
##   .. .. .. ..$ : int [1:2, 1:2] 7 8 8 9
##   .. .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. .. ..$ : NULL
##   .. .. .. .. .. ..$ : NULL
##   .. .. ..@ values.observed        :List of 1
##   .. .. .. ..$ : num [1:2, 1:2] 1 0 0 1
##   .. .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. .. ..$ : NULL
##   .. .. .. .. .. ..$ : NULL
##   .. .. ..@ params.observed        :List of 1
##   .. .. .. ..$ : int [1:2, 1:2] 10 0 0 11
##   .. .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. .. ..$ : NULL
##   .. .. .. .. .. ..$ : NULL
##   .. .. ..@ values.latent.inv.ldl  :List of 1
##   .. .. .. ..$ : num [1:2, 1:2] 0 0 0 0
##   .. .. ..@ values.observed.inv.ldl:List of 1
##   .. .. .. ..$ : num [1:2, 1:2] 0 0 0 0
##   ..@ initial       :Formal class 'dynrInitial' [package "dynr"] with 13 slots
##   .. .. ..@ c.string             : chr "void function_initial_condition(double *param, gsl_vector **co_variate, gsl_vector **pr_0, gsl_vector **eta_0, "| __truncated__
##   .. .. ..@ startval             : num [1:5] 0 0 0 0 0
##   .. .. ..@ paramnames           : chr [1:5] "mu0_1" "mu0_2" "sigma0_11" "sigma0_12" ...
##   .. .. ..@ values.inistate      :List of 1
##   .. .. .. ..$ : num [1:2, 1] 0 0
##   .. .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. .. ..$ : NULL
##   .. .. .. .. .. ..$ : NULL
##   .. .. ..@ params.inistate      :List of 1
##   .. .. .. ..$ : int [1:2, 1] 12 13
##   .. .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. .. ..$ : NULL
##   .. .. .. .. .. ..$ : NULL
##   .. .. ..@ values.inicov        :List of 1
##   .. .. .. ..$ : num [1:2, 1:2] 1 0 0 1
##   .. .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. .. ..$ : NULL
##   .. .. .. .. .. ..$ : NULL
##   .. .. ..@ values.inicov.inv.ldl:List of 1
##   .. .. .. ..$ : num [1:2, 1:2] 0 0 0 0
##   .. .. ..@ params.inicov        :List of 1
##   .. .. .. ..$ : int [1:2, 1:2] 14 15 15 16
##   .. .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. .. ..$ : NULL
##   .. .. .. .. .. ..$ : NULL
##   .. .. ..@ values.regimep       : num [1, 1] 1
##   .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. ..$ : NULL
##   .. .. .. .. ..$ : NULL
##   .. .. ..@ params.regimep       : int [1, 1] 0
##   .. .. .. ..- attr(*, "dimnames")=List of 2
##   .. .. .. .. ..$ : NULL
##   .. .. .. .. ..$ : NULL
##   .. .. ..@ covariates           : chr(0) 
##   .. .. ..@ deviation            : logi FALSE
##   .. .. ..@ refRow               : num(0) 
##   ..@ regimes       :Formal class 'dynrRegimes' [package "dynr"] with 8 slots
##   .. .. ..@ c.string  : chr(0) 
##   .. .. ..@ startval  : num(0) 
##   .. .. ..@ paramnames: chr(0) 
##   .. .. ..@ values    : num[0 , 0 ] 
##   .. .. ..@ params    : num[0 , 0 ] 
##   .. .. ..@ covariates: chr(0) 
##   .. .. ..@ deviation : logi(0) 
##   .. .. ..@ refRow    : num(0) 
##   ..@ transform     :Formal class 'dynrTrans' [package "dynr"] with 9 slots
##   .. .. ..@ c.string     : chr "/**\n * This function modifies some of the parameters so that it satisfies the model constraint.\n * Do not inc"| __truncated__
##   .. .. ..@ startval     : num(0) 
##   .. .. ..@ paramnames   : chr(0) 
##   .. .. ..@ tfun         :function (vec)  
##   .. .. ..@ inv.tfun     :function (vec)  
##   .. .. ..@ inv.tfun.full:function (vec)  
##   .. .. ..@ formula.trans: list()
##   .. .. ..@ formula.inv  : list()
##   .. .. ..@ transCcode   : logi FALSE
##   ..@ data          :List of 8
##   .. ..$ id            : num [1:2500] 1 1 1 1 1 1 1 1 1 1 ...
##   .. ..$ tstart        : int [1:6] 0 500 1000 1500 2000 2500
##   .. ..$ time          : num [1:2500] 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 ...
##   .. ..$ observed      :'data.frame':	2500 obs. of  2 variables:
##   .. .. ..$ obs1: num [1:2500] -1.96 -2.55 -3.27 -4.04 -3.79 ...
##   .. .. ..$ obs2: num [1:2500] 2.53 2.86 2.9 5.18 3.87 ...
##   .. ..$ observed.names: chr [1:2] "y1" "y2"
##   .. ..$ original.data :'data.frame':	2500 obs. of  4 variables:
##   .. .. ..$ id  : num [1:2500] 1 1 1 1 1 1 1 1 1 1 ...
##   .. .. ..$ time: num [1:2500] 0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 ...
##   .. .. ..$ y1  : num [1:2500] -1.96 -2.55 -3.27 -4.04 -3.79 ...
##   .. .. ..$ y2  : num [1:2500] 2.53 2.86 2.9 5.18 3.87 ...
##   .. ..$ idVar         : chr "id"
##   .. ..$ timeVar       : chr "time"
##   ..@ num_regime    : int 1
##   ..@ dim_latent_var: int 2
##   ..@ outfile       : chr "/tmp/RtmpknFpOv/file9894e0df45b.c"
##   ..@ verbose       : logi TRUE
##   ..@ compileLib    : logi TRUE
##   ..@ xstart        : Named num [1:16] 2.11 3.21 0.1 0.1 0.1 ...
##   .. ..- attr(*, "names")= chr [1:16] "mu_1" "mu_2" "phi_11" "phi_21" ...
##   ..@ ub            : Named num [1:16] NA NA NA NA NA NA NA NA NA NA ...
##   .. ..- attr(*, "names")= chr [1:16] "mu_1" "mu_2" "phi_11" "phi_21" ...
##   ..@ lb            : Named num [1:16] NA NA NA NA NA NA NA NA NA NA ...
##   .. ..- attr(*, "names")= chr [1:16] "mu_1" "mu_2" "phi_11" "phi_21" ...
##   ..@ options       :List of 6
##   .. ..$ xtol_rel: num 1e-07
##   .. ..$ stopval : num -9999
##   .. ..$ ftol_rel: num 1e-10
##   .. ..$ ftol_abs: num -1
##   .. ..$ maxeval : int 500
##   .. ..$ maxtime : num -1
##   ..@ param.names   : chr [1:16] "mu_1" "mu_2" "phi_11" "phi_21" ...
```

## Model Fitting


```r
results <- fitOU::FitOU(
  model = model,
  retry = 100,
  verbose = FALSE
)
```

```
## [1] "Get ready!!!!"
## using C compiler: ‘gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0’
## Optimization function called.
## Starting Hessian calculation ...
## Finished Hessian calculation.
## Original exit flag:  3 
## Modified exit flag:  3 
## Optimization terminated successfully: ftol_rel or ftol_abs was reached. 
## Original fitted parameters:  6.709055 6.467322 0.1134668 -0.02238154 -0.1021229 
## 0.06046921 0.9762117 0.022699 1.298896 -0.7015955 -0.7479789 -2.508313 2.076807 
## 0.318909 -0.2958228 0.6088539 
## 
## Transformed fitted parameters:  6.709055 6.467322 0.1134668 -0.02238154 
## -0.1021229 0.06046921 2.654382 0.06025181 3.666615 0.4957936 0.4733222 
## -2.508313 2.076807 1.375626 -0.4069415 1.958706 
## 
## Doing end processing
## Successful trial
## Total Time: 35.16208 
## Backend Time: 34.72212
```

## Summary


```r
summary(results)
```

```
## Coefficients:
##             Estimate Std. Error t value   ci.lower   ci.upper Pr(>|t|)    
## mu_1       6.7090549  3.8684459   1.734 -0.8729598 14.2910696   0.0415 *  
## mu_2       6.4673217  3.8741880   1.669 -1.1259472 14.0605906   0.0476 *  
## phi_11     0.1134668  0.0276020   4.111  0.0593679  0.1675658   <2e-16 ***
## phi_21    -0.0223815  0.0320047  -0.699 -0.0851097  0.0403466   0.2422    
## phi_12    -0.1021229  0.0260145  -3.926 -0.1531104 -0.0511355   <2e-16 ***
## phi_22     0.0604692  0.0306762   1.971  0.0003449  0.1205935   0.0244 *  
## sigma_11   2.6543815  0.2006675  13.228  2.2610804  3.0476826   <2e-16 ***
## sigma_12   0.0602518  0.1387373   0.434 -0.2116682  0.3321718   0.3321    
## sigma_22   3.6666149  0.2610940  14.043  3.1548800  4.1783497   <2e-16 ***
## theta_11   0.4957936  0.0226655  21.874  0.4513701  0.5402172   <2e-16 ***
## theta_22   0.4733222  0.0243865  19.409  0.4255256  0.5211189   <2e-16 ***
## mu0_1     -2.5083132  0.5723104  -4.383 -3.6300210 -1.3866055   <2e-16 ***
## mu0_2      2.0768068  0.6688487   3.105  0.7658875  3.3877261   0.0010 ***
## sigma0_11  1.3756261  1.0480919   1.313 -0.6785964  3.4298485   0.0947 .  
## sigma0_12 -0.4069415  0.8870109  -0.459 -2.1454510  1.3315680   0.3232    
## sigma0_22  1.9587059  1.4324363   1.367 -0.8488176  4.7662295   0.0858 .  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## -2 log-likelihood value at convergence = 14456.05
## AIC = 14488.05
## BIC = 14581.23
```


```
## [1] -2.508313  2.076807
```

### Estimated Coefficients


```r
mu_hat
```

```
## [1] 6.709055 6.467322
```

```r
phi_hat
```

```
##             [,1]        [,2]
## [1,]  0.11346683 -0.10212295
## [2,] -0.02238154  0.06046921
```

```r
sigma_hat
```

```
##            [,1]       [,2]
## [1,] 2.65438152 0.06025181
## [2,] 0.06025181 3.66661487
```

```r
mu0_hat
```

```
## [1] -2.508313  2.076807
```

```r
sigma0_hat
```

```
##            [,1]       [,2]
## [1,]  1.3756261 -0.4069415
## [2,] -0.4069415  1.9587059
```

```r
beta_var1_hat <- as.matrix(
  Matrix::expm(-1 * phi_hat)
)
beta_var1_hat
```

```
##            [,1]       [,2]
## [1,] 0.89377252 0.09366339
## [2,] 0.02052752 0.94237997
```

### Discrepancy Between Estimated and Population Coefficients


```r
abs(mu - mu_hat)
```

```
## [1] 0.9490549 1.2873217
```

```r
abs(phi - phi_hat)
```

```
##            [,1]       [,2]
## [1,] 0.01346683 0.05212295
## [2,] 0.02761846 0.03953079
```

```r
abs(beta_var1 - beta_var1_hat)
```

```
##            [,1]       [,2]
## [1,] 0.01219618 0.04840266
## [2,] 0.02473320 0.03641127
```

```r
abs(sigma - sigma_hat)
```

```
##              [,1]         [,2]
## [1,] 0.1356184810 0.0002518097
## [2,] 0.0002518097 0.3966148689
```







## References
